export default ExpenseCategory = [
  {name: 'Edit', icon: 'lead-pencil', chosen: false, isEdit: true},
  {name: 'Food', icon: 'food', color: '#979797', chosen: false, isEdit: false},
  {name: 'Clothes', icon: 'tshirt-crew', color: '#0100c8', chosen: false, isEdit: false},
  {name: 'Entertain', icon: 'nintendo-game-boy', color: '#feb080', chosen: false, isEdit: false},
  {name: 'Education', icon: 'notebook-edit-outline', color: '#e1fe64', chosen: false, isEdit: false},
  {name: 'Subcription', icon: 'youtube-subscription', color: '#0d9ff5', chosen: false, isEdit: false},
  {name: 'Electricity', icon: 'lightning-bolt', color: '#980ba7', chosen: false, isEdit: false},
  {name: 'Medical', icon: 'medical-bag', color: '#4ed807', chosen: false, isEdit: false},
  {name: 'Telephone', icon: 'cellphone', color: '#000000', chosen: false, isEdit: false},
  {name: 'Travel', icon: 'airplane', color: '#fe0500', chosen: false, isEdit: false},
  {name: 'Cosmestic', icon: 'lipstick', color: '#fd568e', chosen: false, isEdit: false},
  {name: 'Internet', icon: 'wifi', color: '#fc800c', chosen: false, isEdit: false},
  {name: 'Fitness', icon: 'weight-lifter', color: '#41d2c1', chosen: false, isEdit: false},
];