export default IncomeCategory = [
  {id:1, name: 'Edit', chosen: false, isEdit: true},
  {id:2, name: 'Food', chosen: false, isEdit: false},
  {id:3, name: 'Clothes', chosen: false, isEdit: false},
  {id:4, name: 'Entertain', chosen: false, isEdit: false},
  {id:5, name: 'Education', chosen: false, isEdit: false},
  {id:6, name: 'Subcription', chosen: false, isEdit: false},
  {id:7, name: 'Electricity', chosen: false, isEdit: false},
  {id:8, name: 'Medical', chosen: false, isEdit: false},
  {id:9, name: 'Telephone', chosen: false, isEdit: false},
  {id:10, name: 'Travel', chosen: false, isEdit: false},
  {id:11, name: 'Cosmestic', chosen: false, isEdit: false},
  {id:12, name: 'Internet', chosen: false, isEdit: false},
  {id:13, name: 'Fitness', chosen: false, isEdit: false},
];